import { AppSidebar } from "@/components/app-sidebar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-neue font-medium antialiased`}>
        <SidebarProvider>
          <AppSidebar variant="inset" />
          <SidebarInset>
            <div className="p-10">{children}</div>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
